# Generated by Django 6.0.7 on 2026-07-13 16:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createad_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Kategoriya nomi')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Kompaniya/Brend nomi')),
                ('country', models.CharField(max_length=100, verbose_name='Ishlab chiqarilgan mamlakat')),
                ('established_year', models.PositiveIntegerField(verbose_name='Tashkil topgan yili')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createad_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Mahsulot nomi')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Tafsiloti / Tarkibi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2000000)], verbose_name='Narxi')),
                ('image', models.ImageField(default='product.jpg', upload_to='products/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])], verbose_name='Mahsulot rasmi')),
                ('is_available', models.BooleanField(default=True, verbose_name='Sotuvda/Omborda bor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='OziqOvqatlar.category', verbose_name='Kategoriya')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='OziqOvqatlar.manufacturer', verbose_name='Ishlab chiqaruvchi')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
