# Generated by Django 6.0.7 on 2026-07-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Soat nomi')),
                ('brand', models.CharField(max_length=100, verbose_name='Brend')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi ($)')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
