# Generated by Django 6.0.7 on 2026-07-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soatlar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watch',
            options={'verbose_name': 'Watch', 'verbose_name_plural': 'Watches'},
        ),
        migrations.RemoveField(
            model_name='watch',
            name='brand',
        ),
        migrations.AddField(
            model_name='watch',
            name='model',
            field=models.CharField(default='Classic', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watch',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='watch',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterModelTable(
            name='watch',
            table='watches',
        ),
    ]
