# Generated by Django 6.0.7 on 2026-07-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('mileage', models.IntegerField(help_text='km hisobida')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fuel_type', models.CharField(max_length=50)),
            ],
        ),
    ]
